name: Deploy Next.js SSR to GCP VM

on:
  push:
    branches:
      - main  # ganti jika pakai branch lain

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # sesuaikan dengan versimu

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Copy files to GCP VM via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: ".next,package.json,public,pages,next.config.js"
          target: "/home/agenghermawan32/app"

      - name: Run remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/app
            npm install --production
            pm2 restart next || pm2 start npm --name "next" -- start
